//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicFestivalFinderMvc.Models {
	using System;
	using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;
	public partial class MusicFest {
		public int ID
		{
			get; set;
		}
		public string Band
		{
			get; set;
		}
		public string Festival
		{
			get; set;
		}
		public string Location
		{
			get; set;
		}

		[Display(Name = "Date Start")]
		[DataType(DataType.Date)]
		public Nullable<System.DateTime> DateStart
		{
			get; set;
		}

		[Display(Name = "Date End")]
		[DataType(DataType.Date)]
		public Nullable<System.DateTime> DateEnd
		{
			get; set;
		}
	}
}
